### ISSUE TITLE
Error when trying to set number of hidden layers

### ISSUE THREAD

**Issue by illtellyoulater** [irfansharif/cerebrum#15]
Hi, I think you have a little bug in "/lib/cerebrum/cerebrum.rb".

Specifically, in the `train` method you have:

```
    hidden_layer_sizes = [ [3, (input_size/2).floor].max ] unless @hidden_layers
    layer_sizes = [input_size, hidden_layer_sizes, output_size].flatten
```

which causes "hidden_layer_sizes" to be nil when @hidden_layers _exists_ and subsequent methods to fail. Maybe you just forgot to assign it, and you probably wanted something like this:

```
hidden_layer_sizes = [ [3, (input_size/2).floor].max ] unless hidden_layer_sizes = @hidden_layers
```

Is it ok if I make a PR ? Cheers.

**Comment by irfansharif** [comment]
great catch, i think it's a good idea to update `@hidden_layers`. something like this would suffice:

``` ruby
    @hidden_layers ||= [ [3, (input_size/2).floor].max ]
    layer_sizes = [input_size, @hidden_layers, output_size].flatten
```

I'll pull it in if you make a PR for that.

**Comment by illtellyoulater** [comment]
Sure, I agree. I actually thought your original intention was to have a "hidden_layer_sizes =" part in the unless clause, that's why I proposed it, but I agree this is better. Doing it now.
