### ISSUE TITLE
Porting to Crystal

### ISSUE THREAD

**Issue by bararchy** [irfansharif/cerebrum#18]
Hi, 
Your project is really cool, I used it to quickly test hypothesis of ideas and quick checks, but I think it can be more then that.
If you will like the idea of porting to Crystal https://crystal-lang.org/ , I think the network can be much much quicker and can be use for production needs.

Crystal is really similar to Ruby in syntax, so the need for changes should be minimal , if you like that idea and want a helping hand ping me :)

**Comment by irfansharif** [comment]
hey @bararchy, Thank you for looking this over and taking the time to bring up your suggestion, I somehow never got notified of this issue so apologies for the (very) late response! 

Like I mentioned in the README I only used this as an excuse to experiment and play around with the bare fundamentals of neural networks and it has served it's purpose well in that regard. As a result however I don't foresee spending more time on this (as interesting as it'd be to port it over), so unfortunately can't be of much help here. 
If someone decides to take this up and fork cerebrum, I'd be more than happy to walk them through it (it's relatively unintimidating, intentionally so).
